"""add co2_corrected_std to plants

Revision ID: 256334d2a131
Revises: ccbd1fe4693e
Create Date: 2026-08-15 15:30:00.000000
"""
from alembic import op
import sqlalchemy as sa


revision = '256334d2a131'
down_revision = 'ccbd1fe4693e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('co2_corrected_std', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'co2_corrected_std')
    # ### end Alembic commands ###
