"""initial schema

Revision ID: 77a931209592
Revises: 
Create Date: 2026-07-07 04:55:54.288802
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '77a931209592'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_models',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('architecture', sa.String(length=255), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision_score', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_models'))
    )
    op.create_index(op.f('ix_ml_models_version'), 'ml_models', ['version'], unique=True)
    op.create_table('plants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('fuel_type', sa.String(length=50), nullable=False),
    sa.Column('capacity_mw', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plants')),
    sa.UniqueConstraint('external_id', name=op.f('uq_plants_external_id'))
    )
    op.create_index(op.f('ix_plants_country'), 'plants', ['country'], unique=False)
    op.create_index(op.f('ix_plants_name'), 'plants', ['name'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reports_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_table('satellite_images',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('plant_id', sa.Uuid(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('preview_key', sa.String(length=1024), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('bounds', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('crs', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_satellite_images_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_satellite_images_plant_id_plants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_satellite_images')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_satellite_images_storage_key'))
    )
    op.create_index(op.f('ix_satellite_images_owner_id'), 'satellite_images', ['owner_id'], unique=False)
    op.create_index(op.f('ix_satellite_images_plant_id'), 'satellite_images', ['plant_id'], unique=False)
    op.create_table('predictions',
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('schema_version', sa.String(length=10), nullable=False),
    sa.Column('co2_emission_tonnes_per_year', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('hotspots', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('heatmap_key', sa.String(length=1024), nullable=True),
    sa.Column('inference_time_ms', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['satellite_images.id'], name=op.f('fk_predictions_image_id_satellite_images'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], name=op.f('fk_predictions_model_id_ml_models'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_predictions_requested_by_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions'))
    )
    op.create_index('ix_predictions_image_created', 'predictions', ['image_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_predictions_image_id'), 'predictions', ['image_id'], unique=False)
    op.create_index(op.f('ix_predictions_model_id'), 'predictions', ['model_id'], unique=False)
    op.create_index(op.f('ix_predictions_requested_by'), 'predictions', ['requested_by'], unique=False)
    op.create_table('uploads',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('image_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['satellite_images.id'], name=op.f('fk_uploads_image_id_satellite_images'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_uploads_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploads'))
    )
    op.create_index(op.f('ix_uploads_user_id'), 'uploads', ['user_id'], unique=False)
    op.create_table('inference_logs',
    sa.Column('prediction_id', sa.Uuid(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], name=op.f('fk_inference_logs_prediction_id_predictions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inference_logs'))
    )
    op.create_index(op.f('ix_inference_logs_created_at'), 'inference_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_inference_logs_prediction_id'), 'inference_logs', ['prediction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inference_logs_prediction_id'), table_name='inference_logs')
    op.drop_index(op.f('ix_inference_logs_created_at'), table_name='inference_logs')
    op.drop_table('inference_logs')
    op.drop_index(op.f('ix_uploads_user_id'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_predictions_requested_by'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_model_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_image_id'), table_name='predictions')
    op.drop_index('ix_predictions_image_created', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_satellite_images_plant_id'), table_name='satellite_images')
    op.drop_index(op.f('ix_satellite_images_owner_id'), table_name='satellite_images')
    op.drop_table('satellite_images')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_plants_name'), table_name='plants')
    op.drop_index(op.f('ix_plants_country'), table_name='plants')
    op.drop_table('plants')
    op.drop_index(op.f('ix_ml_models_version'), table_name='ml_models')
    op.drop_table('ml_models')
    # ### end Alembic commands ###
