"""add co2 enhancement fields to plants

Revision ID: 9eee376205d4
Revises: 77a931209592
Create Date: 2026-07-10 12:50:01.508540
"""
from alembic import op
import sqlalchemy as sa


revision = '9eee376205d4'
down_revision = '77a931209592'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('co2_enhancement_ppm', sa.Float(), nullable=True))
    op.add_column('plants', sa.Column('co2_bg_std_ppm', sa.Float(), nullable=True))
    op.add_column('plants', sa.Column('co2_no2_peak_km', sa.Float(), nullable=True))
    op.add_column('plants', sa.Column('co2_soundings', sa.Integer(), nullable=True))
    op.add_column('plants', sa.Column('co2_wind_diff_deg', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'co2_wind_diff_deg')
    op.drop_column('plants', 'co2_soundings')
    op.drop_column('plants', 'co2_no2_peak_km')
    op.drop_column('plants', 'co2_bg_std_ppm')
    op.drop_column('plants', 'co2_enhancement_ppm')
    # ### end Alembic commands ###
