"""add ground truth and explainability fields to plants

Revision ID: ccbd1fe4693e
Revises: d3f8a6c15e97
Create Date: 2026-08-15 00:00:00.000000
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = 'ccbd1fe4693e'
down_revision = 'd3f8a6c15e97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('co2_ground_truth_tonnes_per_year', sa.Float(), nullable=True))
    op.add_column('plants', sa.Column('co2_corrected_tonnes_per_year', sa.Float(), nullable=True))
    op.add_column('plants', sa.Column('co2_correction_significant', sa.Boolean(), nullable=True))
    op.add_column('plants', sa.Column('co2_ground_truth_validation_status', sa.String(length=50), nullable=True))
    op.add_column('plants', sa.Column('co2_climate_trace_tonnes', sa.Float(), nullable=True))
    op.add_column('plants', sa.Column('co2_climate_trace_ratio', sa.Float(), nullable=True))
    op.add_column('plants', sa.Column('co2_climate_trace_bracketed', sa.Boolean(), nullable=True))
    op.add_column('plants', sa.Column('detection_exhaustive_lofo_recall', sa.Float(), nullable=True))
    op.add_column('plants', sa.Column('detection_validation_status', sa.String(length=50), nullable=True))
    op.add_column('plants', sa.Column('co2_extended', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'co2_extended')
    op.drop_column('plants', 'detection_validation_status')
    op.drop_column('plants', 'detection_exhaustive_lofo_recall')
    op.drop_column('plants', 'co2_climate_trace_bracketed')
    op.drop_column('plants', 'co2_climate_trace_ratio')
    op.drop_column('plants', 'co2_climate_trace_tonnes')
    op.drop_column('plants', 'co2_ground_truth_validation_status')
    op.drop_column('plants', 'co2_correction_significant')
    op.drop_column('plants', 'co2_corrected_tonnes_per_year')
    op.drop_column('plants', 'co2_ground_truth_tonnes_per_year')
    # ### end Alembic commands ###
